# Generated by Django 5.0 on 2024-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0002_rename_description_customer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Description',
            field=models.TextField(),
        ),
    ]
